# Generated by Django 6.0.7 on 2026-08-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='note_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
